stages:
- name: Criando as Imagens
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sandbox-api:${CICD_EXECUTION_SEQUENCE}
- name: Fazendo deploy no kubernetes
  steps:
  - applyYamlConfig:
      path: ./k8s-manifestos/app-sandbox.yaml
  - applyYamlConfig:
      path: ./k8s-manifestos/banco.yaml
  - applyYamlConfig:
      path: ./k8s-manifestos/ide-theia.yaml
timeout: 120
